/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : sleepModbus.h
**     Project     : FRDM22-M1- Backup - 22.03 - 09.34
**     Processor   : MK22FN512VLH12
**     Component   : Wait
**     Version     : Component 01.069, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-03-29, 09:02, # CodeGen: 0
**     Abstract    :
**          Implements busy waiting routines.
**     Settings    :
**          Component name                                 : sleepModbus
**          SDK                                            : KSDK1
**          Manual Clock Values                            : Disabled
**          Delay100usFunction                             : Delay100US
**          RTOS                                           : Disabled
**          Watchdog                                       : Disabled
**     Contents    :
**         Wait10Cycles   - void sleepModbus_Wait10Cycles(void);
**         Wait100Cycles  - void sleepModbus_Wait100Cycles(void);
**         WaitCycles     - void sleepModbus_WaitCycles(uint16_t cycles);
**         WaitLongCycles - void sleepModbus_WaitLongCycles(uint32_t cycles);
**         Waitms         - void sleepModbus_Waitms(uint16_t ms);
**         Waitus         - void sleepModbus_Waitus(uint16_t us);
**         Waitns         - void sleepModbus_Waitns(uint16_t ns);
**         WaitOSms       - void sleepModbus_WaitOSms(void);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013-2016, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing waiting routines using Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file sleepModbus.h
** @version 01.00
** @brief
**          Implements busy waiting routines.
*/         
/*!
**  @addtogroup sleepModbus_module sleepModbus module documentation
**  @{
*/         

#ifndef __sleepModbus_H
#define __sleepModbus_H

/* MODULE sleepModbus. */

/* Include inherited beans */
#include "KSDK1.h"

#if KSDK1_SDK_VERSION_USED == KSDK1_SDK_VERSION_NONE
/* Include shared modules, which are used for whole project */
  #include "PE_Types.h"
  #include "PE_Error.h"
  #include "PE_Const.h"
  #include "IO_Map.h"
  #include "Cpu.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif


#if KSDK1_SDK_VERSION_USED != KSDK1_SDK_VERSION_NONE
  extern uint32_t SystemCoreClock; /* clock frequency variable defined system_<device>.h of the SDK */
  #define sleepModbus_INSTR_CLOCK_HZ       SystemCoreClock  /* core clock frequency in Hz */
#else
  #define sleepModbus_INSTR_CLOCK_HZ       CPU_CORE_CLK_HZ /* for Kinetis, use core clock as base for instruction execution */
#endif
#define sleepModbus_NofCyclesMs(ms, hz)  ((ms)*((hz)/1000)) /* calculates the needed cycles based on bus clock frequency */
#define sleepModbus_NofCyclesUs(us, hz)  ((us)*(((hz)/1000)/1000)) /* calculates the needed cycles based on bus clock frequency */
#define sleepModbus_NofCyclesNs(ns, hz)  (((ns)*(((hz)/1000)/1000))/1000) /* calculates the needed cycles based on bus clock frequency */


#define sleepModbus_WAIT_C(cycles) \
     ( (cycles)<=10 ? \
          sleepModbus_Wait10Cycles() \
        : sleepModbus_WaitCycles((uint16_t)cycles) \
      )                                      /*!< wait for some cycles */


void sleepModbus_Wait10Cycles(void);
/*
** ===================================================================
**     Method      :  sleepModbus_Wait10Cycles (component Wait)
**     Description :
**         Wait for 10 CPU cycles.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void sleepModbus_Wait100Cycles(void);
/*
** ===================================================================
**     Method      :  sleepModbus_Wait100Cycles (component Wait)
**     Description :
**         Wait for 100 CPU cycles.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void sleepModbus_WaitCycles(uint16_t cycles);
/*
** ===================================================================
**     Method      :  sleepModbus_WaitCycles (component Wait)
**     Description :
**         Wait for a specified number of CPU cycles (16bit data type).
**     Parameters  :
**         NAME            - DESCRIPTION
**         cycles          - The number of cycles to wait.
**     Returns     : Nothing
** ===================================================================
*/

void sleepModbus_Waitms(uint16_t ms);
/*
** ===================================================================
**     Method      :  sleepModbus_Waitms (component Wait)
**     Description :
**         Wait for a specified time in milliseconds.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ms              - How many milliseconds the function has to
**                           wait
**     Returns     : Nothing
** ===================================================================
*/

/* we are having a static clock configuration: implement as macro/inlined version */
#define sleepModbus_Waitus(us)  \
        /*lint -save -e(505,506,522) Constant value Boolean, Redundant left argument to comma. */\
       (  ((sleepModbus_NofCyclesUs((us),sleepModbus_INSTR_CLOCK_HZ)==0)||(us)==0) ? \
          (void)0 : \
          ( ((us)/1000)==0 ? (void)0 : sleepModbus_Waitms((uint16_t)((us)/1000))) \
          , (sleepModbus_NofCyclesUs(((us)%1000), sleepModbus_INSTR_CLOCK_HZ)==0) ? (void)0 : \
            sleepModbus_WAIT_C(sleepModbus_NofCyclesUs(((us)%1000), sleepModbus_INSTR_CLOCK_HZ)) \
       /*lint -restore */\
       )
/*
** ===================================================================
**     Method      :  sleepModbus_Waitus (component Wait)
**     Description :
**         Wait for a specified time in microseconds.
**     Parameters  :
**         NAME            - DESCRIPTION
**         us              - How many microseconds the function has to
**                           wait
**     Returns     : Nothing
** ===================================================================
*/

/* we are having a static clock configuration: implement as macro/inlined version */
#define sleepModbus_Waitns(ns)  \
        /*lint -save -e(505,506,522) Constant value Boolean, Redundant left argument to comma. */\
       (  ((sleepModbus_NofCyclesNs((ns), sleepModbus_INSTR_CLOCK_HZ)==0)||(ns)==0) ? \
          (void)0 : \
          sleepModbus_Waitus((ns)/1000) \
          , (sleepModbus_NofCyclesNs((ns)%1000, sleepModbus_INSTR_CLOCK_HZ)==0) ? \
              (void)0 : \
              sleepModbus_WAIT_C(sleepModbus_NofCyclesNs(((ns)%1000), sleepModbus_INSTR_CLOCK_HZ)) \
       /*lint -restore */\
       )
/*
** ===================================================================
**     Method      :  sleepModbus_Waitns (component Wait)
**     Description :
**         Wait for a specified time in nano seconds.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ns              - How many ns the function has to wait
**     Returns     : Nothing
** ===================================================================
*/

#define sleepModbus_WaitOSms(ms) \
  sleepModbus_Waitms(ms) /* no RTOS used, so use normal wait */
/*
** ===================================================================
**     Method      :  sleepModbus_WaitOSms (component Wait)
**     Description :
**         If an RTOS is enabled, this routine will use a non-blocking
**         wait method. Otherwise it will do a busy/blocking wait.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#ifdef __cplusplus
}  /* extern "C" */
#endif

void sleepModbus_WaitLongCycles(uint32_t cycles);
/*
** ===================================================================
**     Method      :  sleepModbus_WaitLongCycles (component Wait)
**     Description :
**         Wait for a specified number of CPU cycles (32bit data type).
**     Parameters  :
**         NAME            - DESCRIPTION
**         cycles          - The number of cycles to wait.
**     Returns     : Nothing
** ===================================================================
*/

/* END sleepModbus. */

#endif
/* ifndef __sleepModbus_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
